name: crud_cli_dart_project
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.2.1
  uuid: ^4.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  chopper: ^8.3.0
  convert: ^3.1.2
  sqflite: ^2.4.2
  drift: ^2.28.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  drift_dev: ^2.28.0
  chopper_generator: ^8.2.0
  json_serializable: ^6.9.0
  freezed: ^2.4.7

